# Generated by Django 3.2.3 on 2021-05-26 16:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Categoria',
            fields=[
                ('idCategoria', models.IntegerField(primary_key=True, serialize=False, verbose_name='Id de categoria')),
                ('nombreCategoria', models.CharField(max_length=50, verbose_name='Nombre de la categoria')),
            ],
        ),
        migrations.CreateModel(
            name='Producto',
            fields=[
                ('Id', models.CharField(max_length=6, primary_key=True, serialize=False, verbose_name='Id Producto')),
                ('Nombre', models.CharField(max_length=20, verbose_name='Marca')),
                ('Descripcion', models.CharField(blank=True, max_length=200, null=True, verbose_name='Descripcion')),
                ('precio' , models.CharField(max_length=20, null=True, blank=True, verbose_name='Precio')),
                ('categoria', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.categoria')),
            ],
        ),
    ]
 