# Generated by Django 4.0.5 on 2022-06-08 02:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='producto',
            old_name='categoria',
            new_name='Categoria',
        ),
        migrations.AlterField(
            model_name='producto',
            name='Id',
            field=models.CharField(max_length=6, primary_key=True, serialize=False, verbose_name='Id producto'),
        ),
        migrations.AlterField(
            model_name='producto',
            name='Nombre',
            field=models.CharField(max_length=20, verbose_name='Nombre'),
        ),
        migrations.AlterField(
            model_name='producto',
            name='Stock',
            field=models.CharField(max_length=7, verbose_name='Stock'),
        ),
    ]
